version: '4.12'

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DATABASE=database
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - 8000:8000
    # depends_on:
    #   - database
    networks:
      - backend_network
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - frontend_network
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  pgdata:
  app:
