version: '4.33'

volumes:
  postgres_data:
  frontend:

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DATABASE=database
      - POSTGRES_DB=database
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - backend_network
    environment:
      - DJANGO_DB_HOST=database
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=database
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - frontend_network
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/usr/src/app

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
