# Generated by Django 5.0.7 on 2024-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='test',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
