# Generated by Django 5.0.7 on 2024-08-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_decks_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decks',
            old_name='answer',
            new_name='laguange',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='comand',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='laguanje',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='question',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='test',
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='decks.decks')),
            ],
        ),
    ]
