# Generated by Django 5.0.7 on 2024-08-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_alter_decks_category_alter_decks_laguange_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decks',
            old_name='laguange',
            new_name='language',
        ),
    ]
