# Generated by Django 5.0.7 on 2024-08-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_categories_laguange_categories_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='language',
        ),
    ]
