# Generated by Django 5.0.7 on 2024-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_categories_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], default='EN', max_length=200),
        ),
    ]
